language: node_js
node_js:
- '4.1'
notifications:
  email:
    recipients:
    - clay@smockle.com
    on_success: change
    on_failure: always
cache:
  apt: true
  directories:
  - node_modules
addons:
  apt:
    packages:
    - nginx
before_install:
- npm install -g npm@3.3.5
