language: node_js
node_js:
- '4.2.1'
sudo: required
notifications:
  email:
    on_success: change
    on_failure: always
cache:
  apt: true
  directories:
  - node_modules
addons:
  apt:
    packages:
    - nginx
before_install:
- npm install -g npm@3.3.6
before_script:
- sudo useradd nginx
script: sudo nginx -t -c $(pwd)/nginx/nginx.conf
