language: node_js
node_js:
- '4.1'
notifications:
  email:
    recipients:
    - clay@smockle.com
    on_success: change
    on_failure: always
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@3.3.5
