app:
  build: app
  ports:
    - "3000:3000"
blog:
  build: blog
  ports:
    - "2368:2368"
  links:
    - "postgres:postgres"
  env_file: blog/.env
postgres:
  build: postgres
  ports:
    - "5432:5432"
  env_file: postgres/.env
web:
  build: web
  ports:
    - "80:80"
    - "443:443"
  links:
    - "app:app"
    - "blog:blog"
