react:
  build: react
api:
  build: api
  ports:
    - "3000:3000"
worker:
  build: worker
  ports:
    - "4000:4000"
mongo:
  build: mongo
  ports:
    - "27017:27017"
ghost:
  build: ghost
  ports:
    - "2368:2368"
  links:
    - postgres
  env_file: ghost/.env
postgres:
  build: postgres
  ports:
    - "5432:5432"
  env_file: postgres/.env
nginx:
  build: nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - api
    - ghost
    - react
